[target.thumbv6m-none-eabi]
runner = "arm-none-eabi-gdb"

rustflags = [
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tlink.x",
#    "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv6m-none-eabi"
